# Generated by Django 5.2.6 on 2025-09-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='function_name',
            field=models.CharField(default='solve', max_length=50),
        ),
    ]
