# Generated by Django 5.2.6 on 2025-09-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_problem_function_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='function_name',
            field=models.CharField(default='Solution().solve', max_length=50),
        ),
    ]
