# Generated by Django 5.2.6 on 2025-09-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_problem_function_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='error_expected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='error_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='error_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='failed_test',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
