from django.core.management.base import BaseCommand
from main.models import Problem, TestCase

string_problems = [
    {
        'title': 'Reverse Vowels of a String',
        'description': 'Given a string s, reverse only all the vowels in the string and return it.\n\nThe vowels are \'a\', \'e\', \'i\', \'o\', and \'u\', and they can appear in both lower and upper cases.\n\nExample 1:\nInput: s = "hello"\nOutput: "holle"',
        'difficulty': 'Easy',
        'function_name': 'Solution().reverseVowels',
        'test_cases': [
            {'input': '\"hello\"', 'output': '\"holle\"'},
            {'input': '\"leetcode\"', 'output': '\"leotcede\"'},
            {'input': '\"aA\"', 'output': '\"Aa\"'},
            {'input': '\"xyz\"', 'output': '\"xyz\"'}
        ]
    },
    {
        'title': 'Valid Palindrome II',
        'description': 'Given a string s, return true if the s can be palindrome after deleting at most one character from it.\n\nExample 1:\nInput: s = "aba"\nOutput: true\nExample 2:\nInput: s = "abca"\nOutput: true\nExplanation: You could delete the character \'c\'.',
        'difficulty': 'Easy',
        'function_name': 'Solution().validPalindrome',
        'test_cases': [
            {'input': '\"aba\"', 'output': 'true'},
            {'input': '\"abca\"', 'output': 'true'},
            {'input': '\"abc\"', 'output': 'false'},
            {'input': '\"deeee\"', 'output': 'true'}
        ]
    },
    {
        'title': 'Longest Common Prefix',
        'description': 'Write a function to find the longest common prefix string amongst an array of strings.\nIf there is no common prefix, return an empty string "".\n\nExample 1:\nInput: strs = ["flower","flow","flight"]\nOutput: "fl"',
        'difficulty': 'Easy',
        'function_name': 'Solution().longestCommonPrefix',
        'test_cases': [
            {'input': '["flower","flow","flight"]', 'output': '\"fl\"'},
            {'input': '["dog","racecar","car"]', 'output': '\"\"'},
            {'input': '["a"]', 'output': '\"a\"'},
            {'input': '["cir","car"]', 'output': '\"c\"'}
        ]
    },
    {
        'title': 'Valid Parentheses',
        'description': 'Given a string s containing just the characters "(", ")", "{", "}", "[" and "]", determine if the input string is valid.\n\nAn input string is valid if:\n1. Open brackets must be closed by the same type of brackets.\n2. Open brackets must be closed in the correct order.\n\nExample 1:\nInput: s = "()"\nOutput: true',
        'difficulty': 'Easy',
        'function_name': 'Solution().isValid',
        'test_cases': [
            {'input': '\"()\"', 'output': 'true'},
            {'input': '\"()[]{}\"', 'output': 'true'},
            {'input': '\"(]\"', 'output': 'false'},
            {'input': '\"{[]}\"', 'output': 'true'}
        ]
    },
    {
        'title': 'Reverse Words in a String III',
        'description': 'Given a string s, reverse the order of characters in each word within a sentence while still preserving whitespace and initial word order.\n\nExample 1:\nInput: s = "Let\'s take LeetCode contest"\nOutput: "s\'teL ekat edoCteeL tsetnoc"',
        'difficulty': 'Easy',
        'function_name': 'Solution().reverseWords',
        'test_cases': [
            {'input': '\"Let\'s take LeetCode contest\"', 'output': '\"s\'teL ekat edoCteeL tsetnoc\"'},
            {'input': '\"God Ding\"', 'output': '\"doG gniD\"'},
            {'input': '\"a\"', 'output': '\"a\"'},
            {'input': '\"hello world\"', 'output': '\"olleh dlrow\"'}
        ]
    },
    {
        'title': 'Ransom Note',
        'description': 'Given two strings ransomNote and magazine, return true if ransomNote can be constructed by using the letters from magazine and false otherwise.\n\nEach letter in magazine can only be used once in ransomNote.\n\nExample 1:\nInput: ransomNote = "a", magazine = "b"\nOutput: false',
        'difficulty': 'Easy',
        'function_name': 'Solution().canConstruct',
        'test_cases': [
            {'input': '\"a\"\n\"b\"', 'output': 'false'},
            {'input': '\"aa\"\n\"aab\"', 'output': 'true'},
            {'input': '\"aa\"\n\"ab\"', 'output': 'false'},
            {'input': '\"ab\"\n\"aab\"', 'output': 'true'}
        ]
    },
    {
        'title': 'Find the Difference',
        'description': 'You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position.\n\nReturn the letter that was added to t.\n\nExample 1:\nInput: s = "abcd", t = "abcde"\nOutput: "e"\nExplanation: \'e\' is the letter that was added.',
        'difficulty': 'Easy',
        'function_name': 'Solution().findTheDifference',
        'test_cases': [
            {'input': '\"abcd\"\n\"abcde\"', 'output': '\"e\"'},
            {'input': '\"\"\n\"y\"', 'output': '\"y\"'},
            {'input': '\"a\"\n\"aa\"', 'output': '\"a\"'},
            {'input': '\"ae\"\n\"aea\"', 'output': '\"a\"'}
        ]
    },
    {
        'title': 'Valid Palindrome',
        'description': 'A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward. Alphanumeric characters include letters and numbers.\n\nGiven a string s, return true if it is a palindrome, or false otherwise.\n\nExample 1:\nInput: s = "A man, a plan, a canal: Panama"\nOutput: true\nExplanation: "amanaplanacanalpanama" is a palindrome.',
        'difficulty': 'Easy',
        'function_name': 'Solution().isPalindrome',
        'test_cases': [
            {'input': '\"A man, a plan, a canal: Panama\"', 'output': 'true'},
            {'input': '\"race a car\"', 'output': 'false'},
            {'input': '\" \"', 'output': 'true'},
            {'input': '\"0P\"', 'output': 'false'}
        ]
    },
    {
        'title': 'Implement strStr()',
        'description': 'Implement strStr().\n\nGiven two strings needle and haystack, return the index of the first occurrence of needle in haystack, or -1 if needle is not part of haystack.\n\nClarification:\nWhat should we return when needle is an empty string? This is a great question to ask during an interview.\n\nFor the purpose of this problem, we will return 0 when needle is an empty string.\n\nExample 1:\nInput: haystack = "hello", needle = "ll"\nOutput: 2',
        'difficulty': 'Easy',
        'function_name': 'Solution().strStr',
        'test_cases': [
            {'input': '\"hello\"\n\"ll\"', 'output': '2'},
            {'input': '\"aaaaa\"\n\"bba\"', 'output': '-1'},
            {'input': '\"\"\n\"\"', 'output': '0'},
            {'input': '\"abc\"\n\"c\"', 'output': '2'}
        ]
    },
    {
        'title': 'First Unique Character in a String',
        'description': 'Given a string s, find the first non-repeating character in it and return its index. If it does not exist, return -1.\n\nExample 1:\nInput: s = "leetcode"\nOutput: 0',
        'difficulty': 'Easy',
        'function_name': 'Solution().firstUniqChar',
        'test_cases': [
            {'input': '\"leetcode\"', 'output': '0'},
            {'input': '\"loveleetcode\"', 'output': '2'},
            {'input': '\"aabb\"', 'output': '-1'},
            {'input': '\"dddccdbba\"', 'output': '8'}
        ]
    }
]

class Command(BaseCommand):
    help = 'Loads easy string manipulation problems into the database'

    def handle(self, *args, **options):
        for problem_data in string_problems:
            # Check if problem already exists
            if Problem.objects.filter(title=problem_data['title']).exists():
                self.stdout.write(self.style.WARNING(f"Problem '{problem_data['title']}' already exists. Skipping..."))
                continue
                
            # Create the problem
            problem = Problem.objects.create(
                title=problem_data['title'],
                description=problem_data['description'],
                difficulty=problem_data['difficulty'],
                function_name=problem_data['function_name'],
                input_example=problem_data['test_cases'][0]['input'],
                output_example=problem_data['test_cases'][0]['output']
            )
            
            # Add test cases
            for i, test_case in enumerate(problem_data['test_cases']):
                TestCase.objects.create(
                    problem=problem,
                    input_data=test_case['input'],
                    expected_output=test_case['output'],
                    order=i,
                    is_hidden=False
                )
            
            self.stdout.write(self.style.SUCCESS(f"Added problem: {problem_data['title']}"))
        
        self.stdout.write(self.style.SUCCESS('Successfully loaded all string problems!'))
