from django.core.management.base import BaseCommand
from main.models import Problem, Category, TestCase, Example

# 30 ta masala (Oldingi)
PROBLEMS_30 = [
    # 1-30 masalalar (oldingi file'dan)
    {'title': 'Ikkita Sonning Yig\'indisi', 'description': 'Butun sonlardan tuzilgan massiv va target son berilgan. Massivdan shunday ikkita sonni toping, ularning yig\'indisi target songa teng bo\'lsin. Javobda ularning indekslarini qaytaring.', 'difficulty': 'Easy', 'categories': ['Array', 'HashTable'], 'examples': [{'input': 'massiv = [2, 7, 11, 15], target = 9', 'output': '[0, 1]'}, {'input': 'massiv = [3, 2, 4], target = 6', 'output': '[1, 2]'}], 'test_cases': [('[2, 7, 11, 15]\n9', '[0, 1]'), ('[3, 2, 4]\n6', '[1, 2]'), ('[3, 3]\n6', '[0, 1]'), ('[2, 5, 5, 11]\n10', '[1, 2]'), ('[1, 2, 3, 4]\n7', '[2, 3]'), ('[10, 1, 1, 0]\n0', '[2, 3]')]},
    {'title': 'Aktsiyalar Bilan Eng Katta Foyda', 'description': 'Aktsiya narxlari massivi berilgan. Bir marta sotib, bir marta sot qila olasiz. Eng katta foydani hisoblang.', 'difficulty': 'Easy', 'categories': ['Array', 'DynamicProgramming'], 'examples': [{'input': 'narxlar = [7, 1, 5, 3, 6, 4]', 'output': '5 (1 da sotib, 6 da sot)'}, {'input': 'narxlar = [7, 6, 4, 3, 1]', 'output': '0 (foyda yo\'q)'}], 'test_cases': [('[7, 1, 5, 3, 6, 4]', '5'), ('[7, 6, 4, 3, 1]', '0'), ('[2, 4, 1]', '2'), ('[3, 2, 6, 5, 0, 3]', '4'), ('[1]', '0'), ('[1, 2, 3, 4, 5]', '4')]},
    {'title': 'Takroriy Elementni Topish', 'description': 'Butun sonlar massivida takroriy element borligini tekshiring. Agar bir element ikki marta yoki undan ko\'p qo\'llanilib bo\'lsa, True qaytaring.', 'difficulty': 'Easy', 'categories': ['Array', 'HashTable'], 'examples': [{'input': 'massiv = [1, 2, 3, 1]', 'output': 'true'}, {'input': 'massiv = [1, 2, 3, 4]', 'output': 'false'}], 'test_cases': [('[1, 2, 3, 1]', 'true'), ('[1, 2, 3, 4]', 'false'), ('[1, 1, 1, 1]', 'true'), ('[1, 2]', 'false'), ('[99, 99]', 'true'), ('[1, 2, 3, 4, 5]', 'false')]},
    {'title': 'Anagram Tekshirish', 'description': 'Ikkita satrni qabul qiling va ular anagram ekanligini tekshiring. Anagram - bu bir so\'z harflarini qayta joylashtirib boshqa so\'z hosil qilish.', 'difficulty': 'Easy', 'categories': ['String', 'HashTable'], 'examples': [{'input': 's = "anagram", t = "nagaram"', 'output': 'true'}, {'input': 's = "rat", t = "car"', 'output': 'false'}], 'test_cases': [('"anagram"\n"nagaram"', 'true'), ('"rat"\n"car"', 'false'), ('"a"\n"b"', 'false'), ('"ab"\n"ba"', 'true'), ('"abc"\n"cab"', 'true'), ('"listen"\n"silent"', 'true')]},
    {'title': 'Majoriteta Element', 'description': 'Massivda eng ko\'p qo\'llaniladigan elementni toping. Agar n/2 dan ko\'p bo\'lsa, u majoriteta element deyiladi.', 'difficulty': 'Easy', 'categories': ['Array', 'HashTable'], 'examples': [{'input': 'massiv = [3, 2, 3]', 'output': '3'}, {'input': 'massiv = [2, 2, 1, 1, 1, 2, 2]', 'output': '2'}], 'test_cases': [('[3, 2, 3]', '3'), ('[2, 2, 1, 1, 1, 2, 2]', '2'), ('[1]', '1'), ('[2, 2, 2, 1, 1]', '2'), ('[1, 1, 1, 2, 3]', '1'), ('[5, 5, 5, 5, 1]', '5')]},
    {'title': 'Satrni Teskari Qilish', 'description': 'Berilgan satrni teskari qilib, aksariy version qaytaring.', 'difficulty': 'Easy', 'categories': ['String'], 'examples': [{'input': 's = "hello"', 'output': '"olleh"'}, {'input': 's = "abc"', 'output': '"cba"'}], 'test_cases': [('"hello"', '"olleh"'), ('"a"', '"a"'), ('"ab"', '"ba"'), ('"abc"', '"cba"'), ('"racecar"', '"racecar"'), ('"12345"', '"54321"')]},
    {'title': 'Qavslarning To\'g\'riligi', 'description': 'Satr faqat (), {}, [] qavslardan iborat. Ularning to\'g\'ri yopilganligini tekshiring.', 'difficulty': 'Easy', 'categories': ['String', 'Stack'], 'examples': [{'input': 's = "({[]})"', 'output': 'true'}, {'input': 's = "({[}])"', 'output': 'false'}], 'test_cases': [('"({[]})"', 'true'), ('"({[}])"', 'false'), ('"()"', 'true'), ('"(]"', 'false'), ('"([)]"', 'false'), ('"{[]}"', 'true')]},
    {'title': 'Palindrom Tekshirish', 'description': 'Berilgan satr palindrom ekanligini tekshiring. Palindrom - teskari o\'qiganda ham o\'zi bo\'lgan so\'z.', 'difficulty': 'Easy', 'categories': ['String'], 'examples': [{'input': 's = "racecar"', 'output': 'true'}, {'input': 's = "hello"', 'output': 'false'}], 'test_cases': [('"racecar"', 'true'), ('"hello"', 'false'), ('"a"', 'true'), ('"ab"', 'false'), ('"aba"', 'true'), ('"abba"', 'true')]},
    {'title': 'Birinchi Noquli Belgi', 'description': 'Satrdan birinchi takroriy bo\'lmagan belgini toping va uning indeksini qaytaring.', 'difficulty': 'Easy', 'categories': ['String', 'HashTable'], 'examples': [{'input': 's = "leetcode"', 'output': '0'}, {'input': 's = "loveleetcode"', 'output': '2'}], 'test_cases': [('"leetcode"', '0'), ('"loveleetcode"', '2'), ('"aabb"', '-1'), ('"a"', '0'), ('"abc"', '0'), ('"aabcc"', '1')]},
    {'title': 'Eng Uzun Umumiy Prefix', 'description': 'Satrlar massividan barcha satrlar uchun umumiy bo\'lgan eng uzun prefix topilsin.', 'difficulty': 'Easy', 'categories': ['String', 'Array'], 'examples': [{'input': 'strs = ["flower","flow","flight"]', 'output': '"fl"'}, {'input': 'strs = ["dog","racecar","car"]', 'output': '""'}], 'test_cases': [('["flower","flow","flight"]', '"fl"'), ('["dog","racecar","car"]', '""'), ('["interspecies","interstellar","interstate"]', '"inters"'), ('["a"]', '"a"'), ('["ab", "a"]', '"a"'), ('["abc", "abc", "abc"]', '"abc"')]},
    {'title': 'Anagramlarni Guruhlash', 'description': 'Satrlar massivida anagramlarni guruhlang va guruhlangan natijani qaytaring.', 'difficulty': 'Medium', 'categories': ['String', 'HashTable'], 'examples': [{'input': 'strs = ["eat","tea","tan","ate","nat","bat"]', 'output': '[["bat"],["nat","tan"],["ate","eat","tea"]]'}, {'input': 'strs = [""]', 'output': '[[""]]'}], 'test_cases': [('["eat","tea","tan","ate","nat","bat"]', '[["bat"],["nat","tan"],["ate","eat","tea"]]'), ('[""]', '[[""]]'), ('["a"]', '[["a"]]'), ('["ab","ba","abc"]', '[["ab","ba"],["abc"]]'), ('["listen","silent","hello"]', '[["listen","silent"],["hello"]]'), ('["a","b","ab","ba"]', '[["a"],["b"],["ab","ba"]]')]},
    {'title': 'Ikkita Massivning Kesishmasi', 'description': 'Ikkita massiv berilgan. Ularning kesishmadagi elementlarni topib qaytaring. Har bir element bitta marta qaytarilsin.', 'difficulty': 'Easy', 'categories': ['Array', 'HashTable'], 'examples': [{'input': 'nums1 = [1,2,2,1], nums2 = [2,2]', 'output': '[2]'}, {'input': 'nums1 = [4,9,5], nums2 = [9,4,9,8,4]', 'output': '[4,9]'}], 'test_cases': [('[1,2,2,1]\n[2,2]', '[2]'), ('[4,9,5]\n[9,4,9,8,4]', '[4,9]'), ('[1,2]\n[2,3]', '[2]'), ('[1,2,3]\n[2,3,4]', '[2,3]'), ('[]\n[1]', '[]'), ('[1]\n[1]', '[1]')]},
    {'title': 'So\'z Naqshini Tekshirish', 'description': 'Naqsh va satr berilgan. Satr naqshga mos kelishini tekshiring. Har bir harf o\'z naqsh harfiga mos kelishi kerak.', 'difficulty': 'Easy', 'categories': ['String', 'HashTable'], 'examples': [{'input': 'pattern = "abba", s = "redbluebluered"', 'output': 'true'}, {'input': 'pattern = "abba", s = "redbluegreen"', 'output': 'false'}], 'test_cases': [('"abba"\n"redbluebluered"', 'true'), ('"abba"\n"redbluegreen"', 'false'), ('"aaaa"\n"asdasdasdasd"', 'true'), ('"abab"\n"redblueredbluered"', 'false'), ('"a"\n"b"', 'true'), ('"ab"\n"ba"', 'true')]},
    {'title': 'Izomorf Satrlar', 'description': 'Ikkita satr izomorf ekanligini tekshiring. Agar birinchi satrning harflari ikkinchiga o\'xshash tarzda map qilinsa, satrlar izomorf.', 'difficulty': 'Easy', 'categories': ['String', 'HashTable'], 'examples': [{'input': 's = "egg", t = "add"', 'output': 'true'}, {'input': 's = "badc", t = "baba"', 'output': 'false'}], 'test_cases': [('"egg"\n"add"', 'true'), ('"badc"\n"baba"', 'false'), ('"a"\n"b"', 'true'), ('"ab"\n"aa"', 'false'), ('"paper"\n"title"', 'true'), ('"foo"\n"bar"', 'false')]},
    {'title': 'Ransom Note', 'description': 'Ransom note satrini magazine satridan harflardan foydalanib yozish mumkinligini tekshiring.', 'difficulty': 'Easy', 'categories': ['String', 'HashTable'], 'examples': [{'input': 'ransomNote = "a", magazine = "b"', 'output': 'false'}, {'input': 'ransomNote = "a", magazine = "aa"', 'output': 'true'}], 'test_cases': [('"a"\n"b"', 'false'), ('"a"\n"aa"', 'true'), ('"aa"\n"ab"', 'false'), ('"aa"\n"aab"', 'true'), ('"abc"\n"abc"', 'true'), ('"abc"\n"aabbcc"', 'true')]},
    {'title': 'Ikkining Darajasi', 'description': 'Butun son berilgan. Uni 2 ning qaysi darajasi (shuning uchun true/false) tekshiring.', 'difficulty': 'Easy', 'categories': ['Math'], 'examples': [{'input': 'n = 16', 'output': 'true'}, {'input': 'n = 3', 'output': 'false'}], 'test_cases': [('16', 'true'), ('3', 'false'), ('1', 'true'), ('2', 'true'), ('5', 'false'), ('1024', 'true')]},
    {'title': 'Baxtli Raqam', 'description': 'Raqam baxtli deyiladi agar unda har bir raqam bir marta qo\'l kelsa.', 'difficulty': 'Easy', 'categories': ['Math', 'HashTable'], 'examples': [{'input': 'n = 123', 'output': 'true'}, {'input': 'n = 1223', 'output': 'false'}], 'test_cases': [('123', 'true'), ('1223', 'false'), ('1', 'true'), ('1023456789', 'true'), ('1023456780', 'false'), ('121', 'false')]},
    {'title': 'To\'g\'ri Sempurna Kvadrat', 'description': 'Raqam to\'g\'ri sempurna kvadrat ekanligini tekshiring (masalan, 4, 9, 16).', 'difficulty': 'Easy', 'categories': ['Math'], 'examples': [{'input': 'num = 16', 'output': 'true'}, {'input': 'num = 17', 'output': 'false'}], 'test_cases': [('16', 'true'), ('17', 'false'), ('1', 'true'), ('0', 'true'), ('9', 'true'), ('10', 'false')]},
    {'title': 'Xunuk Raqam', 'description': 'Raqam xunuk deyiladi agar uning raqamlarining kvadratlari yig\'indisi 1 ga teng bo\'lguncha siklda takrorlanmasa.', 'difficulty': 'Easy', 'categories': ['Math', 'DynamicProgramming'], 'examples': [{'input': 'n = 2', 'output': 'false'}, {'input': 'n = 7', 'output': 'true'}], 'test_cases': [('2', 'false'), ('7', 'true'), ('10', 'false'), ('19', 'true'), ('1', 'true'), ('0', 'false')]},
    {'title': 'Yo\'q Bo\'lgan Raqam', 'description': 'n+1 ta raqam massivida 0 dan n gacha bo\'lgan raqamlar berilgan. Yo\'q bo\'lgan raqamni toping.', 'difficulty': 'Easy', 'categories': ['Array', 'Math'], 'examples': [{'input': 'nums = [3,0,1]', 'output': '2'}, {'input': 'nums = [0,1]', 'output': '2'}], 'test_cases': [('[3,0,1]', '2'), ('[0,1]', '2'), ('[9,6,4,2,3,5,7,0,1]', '8'), ('[0]', '1'), ('[1]', '0'), ('[1,2,0]', '3')]},
    {'title': 'Minimal Stek', 'description': 'Har bir element uchun o\'ngdagi eng kichik elementni toping. Natijaviy o\'ng massivi qaytaring.', 'difficulty': 'Medium', 'categories': ['Stack'], 'examples': [{'input': 'temps = [73,74,75,71,69,72,76,73]', 'output': '[1,1,4,2,1,1,0,0]'}, {'input': 'temps = [30,40,50,60]', 'output': '[1,1,1,0]'}], 'test_cases': [('[73,74,75,71,69,72,76,73]', '[1,1,4,2,1,1,0,0]'), ('[30,40,50,60]', '[1,1,1,0]'), ('[34,80,80,34,34,80,80,80,80,34]', '[1,0,0,0,0,0,0,0,0,0]'), ('[1,2,3]', '[1,1,0]'), ('[3,2,1]', '[0,0,0]'), ('[100]', '[0]')]},
    {'title': 'Reverse Polish Notation Baholash', 'description': 'Reverse Polish Notation operatorlari massivini baholang va natija qaytaring.', 'difficulty': 'Medium', 'categories': ['Array', 'Math', 'Stack'], 'examples': [{'input': 'tokens = ["2","1","+","3","*"]', 'output': '9'}, {'input': 'tokens = ["4","13","5","/","+"]', 'output': '6'}], 'test_cases': [('["2","1","+","3","*"]', '9'), ('["4","13","5","/","+"]', '6'), ('["15","7","1","+","/","3","*","2","-"]', '5'), ('["2","3","+"]', '5'), ('["10"]', '10'), ('["2","3","*"]', '6')]},
    {'title': 'Kunlik Haroratlar', 'description': 'Har bir kun uchun o\'ngda isik ko\'p bo\'lgan kunni toping. Kunlar sonini qaytaring.', 'difficulty': 'Medium', 'categories': ['Array', 'Stack'], 'examples': [{'input': 'temperatures = [73,74,75,71,69,72,76,73]', 'output': '[1,1,4,2,1,1,0,0]'}, {'input': 'temperatures = [30,40,50,60]', 'output': '[1,1,1,0]'}], 'test_cases': [('[73,74,75,71,69,72,76,73]', '[1,1,4,2,1,1,0,0]'), ('[30,40,50,60]', '[1,1,1,0]'), ('[34,80,80,34,34,80,80,80,80,34]', '[1,0,0,0,0,0,0,0,0,0]'), ('[1,2,3]', '[1,1,0]'), ('[3,2,1]', '[0,0,0]'), ('[100]', '[0]')]},
    {'title': 'Yo\'g\'un Suv', 'description': 'Balandlik massivida eng ko\'p suvni qamashuvchi kontejner topilsin. Suvning hajmi qaytaring.', 'difficulty': 'Hard', 'categories': ['Array', 'DynamicProgramming', 'Stack'], 'examples': [{'input': 'height = [1,8,6,2,5,4,8,3,7]', 'output': '49'}, {'input': 'height = [1,1]', 'output': '1'}], 'test_cases': [('[1,8,6,2,5,4,8,3,7]', '49'), ('[1,1]', '1'), ('[2,3,4,5,18,17,6]', '17'), ('[4,3,2,1,4]', '16'), ('[1,2,1]', '2'), ('[3,9,3,4,7,2,12,6]', '45')]},
    {'title': 'Gistogramming Eng Katta To\'rtburchak', 'description': 'Gistogramm ustunlarida eng katta to\'rtburchakning maydonini topilsin.', 'difficulty': 'Hard', 'categories': ['Stack'], 'examples': [{'input': 'heights = [2,1,5,6,2,3]', 'output': '10'}, {'input': 'heights = [2,4]', 'output': '4'}], 'test_cases': [('[2,1,5,6,2,3]', '10'), ('[2,4]', '4'), ('[1]', '1'), ('[1,1,1,1]', '4'), ('[1,2,2,1]', '4'), ('[0,2,0]', '2')]},
    {'title': 'Binary Daraxt Darajali Traversal', 'description': 'Binary daraxtni daraj-daraj traversal qilib, natijani qaytaring.', 'difficulty': 'Medium', 'categories': ['Tree', 'Queue'], 'examples': [{'input': 'root = [3,9,20,null,null,15,7]', 'output': '[[3],[9,20],[15,7]]'}, {'input': 'root = [1]', 'output': '[[1]]'}], 'test_cases': [('[3,9,20,null,null,15,7]', '[[3],[9,20],[15,7]]'), ('[1]', '[[1]]'), ('[1,2,3,4,5,6,7]', '[[1],[2,3],[4,5,6,7]]'), ('[]', '[]'), ('[1,2]', '[[1],[2]]'), ('[1,null,2]', '[[1],[2]]')]},
    {'title': 'Yig\'undi Yo\'li', 'description': 'Root dan leaf gacha yo\'llar uchun eng katta yig\'indini topilsin.', 'difficulty': 'Easy', 'categories': ['Tree'], 'examples': [{'input': 'root = [1,2,3]', 'output': '6'}, {'input': 'root = [1,2]', 'output': '3'}], 'test_cases': [('[1,2,3]', '6'), ('[1,2]', '3'), ('[1]', '1'), ('[9,9,9]', '27'), ('[5,4,11,null,null,7,2]', '18'), ('[1,2,3,4,null,null,5]', '9')]},
    {'title': 'Binary Daraxtning Maksimal Chuqurligi', 'description': 'Binary daraxtning maksimal chuqurligi topilsin.', 'difficulty': 'Easy', 'categories': ['Tree'], 'examples': [{'input': 'root = [3,9,20,null,null,15,7]', 'output': '3'}, {'input': 'root = [2,null,3]', 'output': '2'}], 'test_cases': [('[3,9,20,null,null,15,7]', '3'), ('[2,null,3]', '2'), ('[]', '0'), ('[1]', '1'), ('[1,2,3,4,5,null,6]', '4'), ('[0]', '1')]},
    {'title': 'Binary Qidiruv Daraxti Tekshirish', 'description': 'Daraxt Binary Qidiruv Daraxti ekanligini tekshiring.', 'difficulty': 'Medium', 'categories': ['Tree'], 'examples': [{'input': 'root = [2,1,3]', 'output': 'true'}, {'input': 'root = [5,1,4,null,null,4,6]', 'output': 'false'}], 'test_cases': [('[2,1,3]', 'true'), ('[5,1,4,null,null,4,6]', 'false'), ('[1]', 'true'), ('[5,null,15,null,20]', 'true'), ('[1,null,1]', 'true'), ('[32,26,47,19,null,null,56,16,27,null,null,54]', 'false')]},
    {'title': 'Binary Qidiruv Daraxti ning Eng Kichik Umumiy Atasi', 'description': 'Binary Qidiruv Daraxti uchun ikkita tugunning eng kichik umumiy atasi topilsin.', 'difficulty': 'Medium', 'categories': ['Tree'], 'examples': [{'input': 'root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 8', 'output': '6'}, {'input': 'root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 4', 'output': '2'}], 'test_cases': [('[6,2,8,0,4,7,9,null,null,3,5]', '6'), ('[6,2,8,0,4,7,9,null,null,3,5]', '2'), ('[2,1]', '2'), ('[6,2,8,0,4,7,9]', '6'), ('[1,0]', '1'), ('[37,24,44,12,36,31,47,8,16,28,40,null,null,26,42]', '37')]},
]

# 20 ta yangi masala
PROBLEMS_20 = [
    {'title': 'Massiv Yig\'indisi', 'description': 'Berilgan massivdagi barcha sonlarning yig\'indisini hisoblang.', 'difficulty': 'Easy', 'categories': ['Array'], 'examples': [{'input': 'nums = [1, 2, 3, 4, 5]', 'output': '15'}, {'input': 'nums = [10, 20, 30]', 'output': '60'}], 'test_cases': [('[1, 2, 3, 4, 5]', '15'), ('[10, 20, 30]', '60'), ('[0]', '0'), ('[1]', '1'), ('[-1, -2, -3]', '-6'), ('[100, 200, 300]', '600'), ('[]', '0')]},
    {'title': 'Eng Katta Element', 'description': 'Massivdagi eng katta sonni toping.', 'difficulty': 'Easy', 'categories': ['Array'], 'examples': [{'input': 'nums = [3, 7, 2, 9, 1]', 'output': '9'}, {'input': 'nums = [1]', 'output': '1'}], 'test_cases': [('[3, 7, 2, 9, 1]', '9'), ('[1]', '1'), ('[5, 5, 5, 5]', '5'), ('[1, 2, 3, 4, 5]', '5'), ('[-5, -1, -10]', '-1'), ('[100, 50, 75]', '100'), ('[0, 0, 0]', '0')]},
    {'title': 'Eng Kichik Element', 'description': 'Massivdagi eng kichik sonni toping.', 'difficulty': 'Easy', 'categories': ['Array'], 'examples': [{'input': 'nums = [3, 7, 2, 9, 1]', 'output': '1'}, {'input': 'nums = [5, 4, 3, 2, 1]', 'output': '1'}], 'test_cases': [('[3, 7, 2, 9, 1]', '1'), ('[5, 4, 3, 2, 1]', '1'), ('[10]', '10'), ('[5, 5, 5]', '5'), ('[-1, -5, -3]', '-5'), ('[100, 50, 75]', '50'), ('[0, 0, 1]', '0')]},
    {'title': 'Satr Uzunligi', 'description': 'Berilgan satrning uzunligini qaytaring (bo\'sh joylar ham sanaladdi).', 'difficulty': 'Easy', 'categories': ['String'], 'examples': [{'input': 's = "hello"', 'output': '5'}, {'input': 's = "a b c"', 'output': '5'}], 'test_cases': [('"hello"', '5'), ('"a b c"', '5'), ('""', '0'), ('"a"', '1'), ('"hello world"', '11'), ('"12345"', '5'), ('"   "', '3')]},
    {'title': 'Raqam Juft yoki Toq', 'description': 'Berilgan raqam juft yoki toq ekanligini aniqlang. Juft bo\'lsa "Juft", toq bo\'lsa "Toq" qaytaring.', 'difficulty': 'Easy', 'categories': ['Math'], 'examples': [{'input': 'n = 4', 'output': '"Juft"'}, {'input': 'n = 7', 'output': '"Toq"'}], 'test_cases': [('4', '"Juft"'), ('7', '"Toq"'), ('0', '"Juft"'), ('1', '"Toq"'), ('100', '"Juft"'), ('999', '"Toq"'), ('2', '"Juft"')]},
    {'title': 'Ikkita Raqam Yig\'indisi', 'description': 'Ikkita raqamni qabul qilib, ularning yig\'indisini qaytaring.', 'difficulty': 'Easy', 'categories': ['Math'], 'examples': [{'input': 'a = 5, b = 3', 'output': '8'}, {'input': 'a = -1, b = 1', 'output': '0'}], 'test_cases': [('5\n3', '8'), ('-1\n1', '0'), ('0\n0', '0'), ('10\n20', '30'), ('-5\n-3', '-8'), ('100\n1', '101'), ('7\n2', '9')]},
    {'title': 'Ikkita Raqam Ayirmasi', 'description': 'Birinchi raqamdan ikkinchi raqamni ayiring.', 'difficulty': 'Easy', 'categories': ['Math'], 'examples': [{'input': 'a = 10, b = 3', 'output': '7'}, {'input': 'a = 5, b = 5', 'output': '0'}], 'test_cases': [('10\n3', '7'), ('5\n5', '0'), ('0\n0', '0'), ('20\n5', '15'), ('-5\n3', '-8'), ('1\n-1', '2'), ('100\n1', '99')]},
    {'title': 'Ikkita Raqam Ko\'paytmasi', 'description': 'Ikkita raqamni ko\'paytiring va natijani qaytaring.', 'difficulty': 'Easy', 'categories': ['Math'], 'examples': [{'input': 'a = 4, b = 5', 'output': '20'}, {'input': 'a = 0, b = 10', 'output': '0'}], 'test_cases': [('4\n5', '20'), ('0\n10', '0'), ('1\n1', '1'), ('7\n8', '56'), ('-3\n4', '-12'), ('10\n10', '100'), ('2\n3', '6')]},
    {'title': 'Satrni Bosh Harfga O\'girish', 'description': 'Satrning birinchi harfini bosh harfga o\'giring. Agar satr bo\'sh bo\'lsa, bo\'sh satr qaytaring.', 'difficulty': 'Easy', 'categories': ['String'], 'examples': [{'input': 's = "hello"', 'output': '"Hello"'}, {'input': 's = "WORLD"', 'output': '"World"'}], 'test_cases': [('"hello"', '"Hello"'), ('"WORLD"', '"World"'), ('"a"', '"A"'), ('"abc"', '"Abc"'), ('"123abc"', '"123abc"'), ('"HeLLo"', '"HeLLo"'), ('"hELLO"', '"HeLLO"')]},
    {'title': 'Massivdagi Elementlar Soni', 'description': 'Massivning uzunligini (elementlar sonini) qaytaring.', 'difficulty': 'Easy', 'categories': ['Array'], 'examples': [{'input': 'nums = [1, 2, 3, 4, 5]', 'output': '5'}, {'input': 'nums = []', 'output': '0'}], 'test_cases': [('[1, 2, 3, 4, 5]', '5'), ('[]', '0'), ('[1]', '1'), ('[1, 2, 3]', '3'), ('[10, 20, 30, 40]', '4'), ('[0, 0, 0, 0, 0]', '5'), ('[1, 1, 1, 1, 1, 1, 1]', '7')]},
    {'title': 'Raqamni Ikki Barobar Qilish', 'description': 'Berilgan raqamni 2 ga ko\'paytiring.', 'difficulty': 'Easy', 'categories': ['Math'], 'examples': [{'input': 'n = 5', 'output': '10'}, {'input': 'n = 0', 'output': '0'}], 'test_cases': [('5', '10'), ('0', '0'), ('1', '2'), ('10', '20'), ('-3', '-6'), ('100', '200'), ('7', '14')]},
    {'title': 'Massivni Teskarisiga O\'girish', 'description': 'Berilgan massivni teskari tartibda qaytaring.', 'difficulty': 'Easy', 'categories': ['Array'], 'examples': [{'input': 'nums = [1, 2, 3, 4, 5]', 'output': '[5, 4, 3, 2, 1]'}, {'input': 'nums = [1]', 'output': '[1]'}], 'test_cases': [('[1, 2, 3, 4, 5]', '[5, 4, 3, 2, 1]'), ('[1]', '[1]'), ('[]', '[]'), ('[1, 2, 3]', '[3, 2, 1]'), ('[5, 5, 5]', '[5, 5, 5]'), ('[1, 2]', '[2, 1]'), ('[10, 20, 30, 40]', '[40, 30, 20, 10]')]},
    {'title': 'Nol Bilan Tugashini Tekshiring', 'description': 'Raqamning oxirgi raqami nol bilan tugashini tekshiring.', 'difficulty': 'Easy', 'categories': ['Math'], 'examples': [{'input': 'n = 120', 'output': 'true'}, {'input': 'n = 123', 'output': 'false'}], 'test_cases': [('120', 'true'), ('123', 'false'), ('0', 'true'), ('10', 'true'), ('100', 'true'), ('999', 'false'), ('50', 'true')]},
    {'title': 'Raqamning Mutloq Qiymati', 'description': 'Berilgan raqamning mutloq qiymatini (absolute value) qaytaring.', 'difficulty': 'Easy', 'categories': ['Math'], 'examples': [{'input': 'n = -5', 'output': '5'}, {'input': 'n = 10', 'output': '10'}], 'test_cases': [('-5', '5'), ('10', '10'), ('0', '0'), ('-100', '100'), ('1', '1'), ('-1', '1'), ('-999', '999')]},
    {'title': 'Berilgan Target Yig\'indining Soni', 'description': 'Massivda target songa teng yig\'indining necha xil juftlik bor, uni hisoblang.', 'difficulty': 'Medium', 'categories': ['Array', 'HashTable'], 'examples': [{'input': 'nums = [1, 5, 7, -1, 5], target = 5', 'output': '2'}, {'input': 'nums = [1, 1, 1, 1], target = 2', 'output': '6'}], 'test_cases': [('[1, 5, 7, -1, 5]\n5', '2'), ('[1, 1, 1, 1]\n2', '6'), ('[0, 0]\n0', '1'), ('[1, 2, 3]\n5', '2'), ('[1]\n1', '0'), ('[1, 1, 1, 1, 1]\n2', '10'), ('[2, 3, 4]\n6', '1')]},
    {'title': '3 ta Sonning Yig\'indisi Nolga Teng', 'description': 'Massivda 3 ta sonni topingki, ularning yig\'indisi 0 ga teng bo\'lsin. Takroriy bo\'lmagan juftliklarni qaytaring.', 'difficulty': 'Medium', 'categories': ['Array', 'HashTable'], 'examples': [{'input': 'nums = [-1, 0, 1, 2, -1, -4]', 'output': '[[-1, -1, 2], [-1, 0, 1]]'}, {'input': 'nums = [0, 0, 0, 0]', 'output': '[[0, 0, 0]]'}], 'test_cases': [('[-1, 0, 1, 2, -1, -4]', '[[-1, -1, 2], [-1, 0, 1]]'), ('[0, 0, 0, 0]', '[[0, 0, 0]]'), ('[-2, 0, 1, 1, 2]', '[[-2, 0, 2], [-2, 1, 1]]'), ('[-1, -1, -1, 0, 1, 2]', '[[-1, -1, 2], [-1, 0, 1]]'), ('[0]', '[]'), ('[-1, 0, 1]', '[[-1, 0, 1]]'), ('[1, -2, -1, 0, 2]', '[[-2, 0, 2], [-1, 0, 1]]')]},
    {'title': 'Massivning O\'rtacha Qiymati', 'description': 'Massivning o\'rtacha (average) qiymatini hisoblang. Agar massiv bo\'sh bo\'lsa, 0 qaytaring.', 'difficulty': 'Medium', 'categories': ['Array', 'Math'], 'examples': [{'input': 'nums = [1, 2, 3, 4, 5]', 'output': '3.0'}, {'input': 'nums = [10, 20, 30]', 'output': '20.0'}], 'test_cases': [('[1, 2, 3, 4, 5]', '3.0'), ('[10, 20, 30]', '20.0'), ('[5]', '5.0'), ('[0]', '0.0'), ('[1, 1, 1, 1]', '1.0'), ('[2, 4, 6, 8]', '5.0'), ('[1, 2, 3]', '2.0')]},
    {'title': 'Massivda Eng Katta Qo\'shni Yig\'indisining Farqi', 'description': 'Massivda eng katta qo\'shni (ketma-ket) ikkita elementning yig\'indisining farqini toping.', 'difficulty': 'Hard', 'categories': ['Array', 'DynamicProgramming'], 'examples': [{'input': 'nums = [1, 3, -1, -3, 5, 3, 4, -2]', 'output': '8'}, {'input': 'nums = [1, 2, 3, 4]', 'output': '3'}], 'test_cases': [('[1, 3, -1, -3, 5, 3, 4, -2]', '8'), ('[1, 2, 3, 4]', '3'), ('[1, 1, 1, 1]', '0'), ('[5, -3, 4, -1, 2]', '6'), ('[1, -1, 1, -1]', '2'), ('[-5, -2, -3, -1]', '4'), ('[10, 5, 8, 3, 2]', '7')]},
    {'title': 'Eng Katta Subarray Yig\'indisi', 'description': 'Massivning ketma-ket qismi (subarray) ning eng katta yig\'indisini toping.', 'difficulty': 'Hard', 'categories': ['Array', 'DynamicProgramming'], 'examples': [{'input': 'nums = [-2, 1, -3, 4, -1, 2, 1, -5, 4]', 'output': '6'}, {'input': 'nums = [1]', 'output': '1'}], 'test_cases': [('[-2, 1, -3, 4, -1, 2, 1, -5, 4]', '6'), ('[1]', '1'), ('[-1]', '-1'), ('[5, -3, 5]', '7'), ('[-2, -1, -3, -4]', '-1'), ('[2, -1, 2, -1, 4, -5]', '6'), ('[1, 2, 3, 4, 5]', '15')]},
    {'title': 'Massivda Maksimal Profit', 'description': 'Massiv narxlardan eng katta foydani topish uchun bir marta sotib, bir marta sotish orqali maksimal profit hisoblang.', 'difficulty': 'Hard', 'categories': ['Array', 'DynamicProgramming'], 'examples': [{'input': 'prices = [3, 2, 6, 5, 0, 3]', 'output': '4'}, {'input': 'prices = [7, 6, 4, 3, 1]', 'output': '0'}], 'test_cases': [('[3, 2, 6, 5, 0, 3]', '4'), ('[7, 6, 4, 3, 1]', '0'), ('[2, 4, 1]', '2'), ('[1, 2, 3, 4, 5]', '4'), ('[5, 4, 3, 2, 1]', '0'), ('[1, 5, 2, 3, 4]', '4'), ('[3, 3, 5, 0, 0, 3, 1, 4]', '4')]},
]

class Command(BaseCommand):
    help = 'Load all 50 problems (30 original + 20 new)'

    def handle(self, *args, **options):
        Problem.objects.all().delete()

        categories_map = {}
        for cat in Category.objects.all():
            categories_map[cat.name] = cat

        all_problems = PROBLEMS_30 + PROBLEMS_20

        self.stdout.write('📚 50 ta masala qo\'shilyapti...\n')

        for i, problem_data in enumerate(all_problems, 1):
            problem = Problem.objects.create(
                title=problem_data['title'],
                description=problem_data['description'],
                difficulty=problem_data['difficulty'],
                function_name='Solution().solve',
                input_example=problem_data.get('input_example', ''),
                output_example=problem_data.get('output_example', ''),
            )

            cat_names = ', '.join(problem_data['categories'])
            for cat_name in problem_data['categories']:
                if cat_name in categories_map:
                    problem.categories.add(categories_map[cat_name])

            for example in problem_data['examples']:
                Example.objects.create(
                    problem=problem,
                    ex_input=example['input'],
                    ex_output=example['output']
                )

            for j, (inp, out) in enumerate(problem_data['test_cases'], 1):
                TestCase.objects.create(
                    problem=problem,
                    input_data=inp,
                    expected_output=out,
                    order=j
                )

            if i % 10 == 0:
                self.stdout.write(f'✅ {i} ta masala qo\'shildi')

        self.stdout.write('\n✅ HAMMASINI TAYYORLANDI!')
        self.stdout.write('✅ Jami: 50 ta masala')
        self.stdout.write('✅ 30 original + 20 yangi')
        self.stdout.write('✅ Har biri uchun kamida 6-7 ta test case')
        self.stdout.write('🎉 Database tayyor!')
